sudo: false
language: node_js
node_js: 6
branches:
  only:
    master
notifications:
  email:
    - darinallen@gmail.com
    - faizmohammed178@gmail.com
    - mohammad.farooqi@gmail.com
    - alexrosenthalster@gmail.com
script:
  npm run test
